pipeline {
    agent any
    tools {
        sonarQube 'SonarQube Scanner 3.3'
    }
    stages {
        stage('SonarQube analysis') {
            tools {
                sonarQube 'SonarQube Scanner 3.3'
            }
            withSonarQubeEnv('SonarQube Scanner 3.3') {
               sh 'mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:sonar'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
